# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-09 02:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IP',
            fields=[
                ('ip_id', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=16)),
                ('description', models.CharField(max_length=64)),
                ('address', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='PLC',
            fields=[
                ('plc_id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('tag', models.CharField(max_length=8)),
                ('ip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.IP')),
            ],
        ),
    ]
