# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-05 16:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('DBRoll', models.CharField(max_length=32, null=True)),
                ('SFCERoll', models.CharField(max_length=32, null=True)),
                ('INCERoll', models.CharField(max_length=32, null=True)),
                ('SFBRoll', models.CharField(max_length=32, null=True)),
                ('INBRoll', models.CharField(max_length=32, null=True)),
                ('CorrData', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.CorrData')),
            ],
        ),
    ]
