# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-27 03:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('UTSPWrapPercentage', models.IntegerField(null=True)),
                ('LTSPCCW', models.IntegerField(null=True)),
                ('UTSPCW', models.IntegerField(null=True)),
                ('TempLowOpAS', models.FloatField(null=True)),
                ('UTSPOver', models.NullBooleanField()),
                ('Moisture', models.FloatField(null=True)),
                ('LTSPOver', models.NullBooleanField()),
                ('Shoe6', models.IntegerField(null=True)),
                ('Shoe7', models.IntegerField(null=True)),
                ('Shoe4', models.IntegerField(null=True)),
                ('Shoe5', models.IntegerField(null=True)),
                ('Shoe2', models.IntegerField(null=True)),
                ('Shoe3', models.IntegerField(null=True)),
                ('Shoe1', models.IntegerField(null=True)),
                ('MTSPCW', models.IntegerField(null=True)),
                ('Shoe8', models.IntegerField(null=True)),
                ('Shoe9', models.IntegerField(null=True)),
                ('TempLinerLowDrBefHP', models.FloatField(null=True)),
                ('TempUpDrAS', models.FloatField(null=True)),
                ('TempLowDrAS', models.FloatField(null=True)),
                ('LTSPCW', models.IntegerField(null=True)),
                ('Shoe10', models.IntegerField(null=True)),
                ('MTSPCCW', models.IntegerField(null=True)),
                ('TempLinerLowOpBefHP', models.FloatField(null=True)),
                ('TempLinerUpOpBefGM', models.FloatField(null=True)),
                ('UTSPCCW', models.IntegerField(null=True)),
                ('LTSPWrapPercentage', models.IntegerField(null=True)),
                ('TempUpOpAS', models.FloatField(null=True)),
                ('MTSPWrapPercentage', models.FloatField(null=True)),
                ('TempLinerUpDrBefGM', models.FloatField(null=True)),
            ],
        ),
    ]
