# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-05 23:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_recipe'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='CorrData',
            new_name='CorrDataID',
        ),
        migrations.AddField(
            model_name='recipe',
            name='BotOrder',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='BotOrder_CustomerName',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='DBRoll_FakeWeight',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='DBRoll_TagWeight',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='DBRoll_Vendor',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='INBRoll_FakeWeight',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='INBRoll_TagWeight',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='INBRoll_Vendor',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='INCERoll_FakeWeight',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='INCERoll_TagWeight',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='INCERoll_Vendor',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='IsLabTest',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='recipe',
            name='RecipeCardTitle',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='SFBRoll_FakeWeight',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='SFBRoll_TagWeight',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='SFBRoll_Vendor',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='SFCERoll_FakeWeight',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='SFCERoll_TagWeight',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='SFCERoll_Vendor',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='TopOrder',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='TopOrder_CustomerName',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
