# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-27 03:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_db'),
    ]

    operations = [
        migrations.AddField(
            model_name='db',
            name='MTSPOver',
            field=models.NullBooleanField(),
        ),
    ]
