# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-27 02:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20170511_2123'),
    ]

    operations = [
        migrations.AddField(
            model_name='corrdata',
            name='Shear11P7A',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='corrdata',
            name='Shear3P11P',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='corrdata',
            name='Shear7A3P',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='corrdata',
            name='ShearCurrent',
            field=models.IntegerField(null=True),
        ),
    ]
