# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-25 12:39
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20170626_2216'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpliceAtom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Datetime', models.DateTimeField(default=datetime.datetime.utcnow)),
                ('AtomType', models.CharField(choices=[('DBSplice', 'Double backer'), ('BFLSplice', 'B-flute liner'), ('BFMSplice', 'B-flute medium'), ('CEFMSplice', 'C/E-flute medium'), ('CEFLSplice', 'C/E-flute linear')], max_length=12)),
                ('Value', models.IntegerField()),
            ],
        ),
    ]
