# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-27 21:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_spliceatom'),
    ]

    operations = [
        migrations.AddField(
            model_name='spliceatom',
            name='MinSpeed',
            field=models.IntegerField(null=True),
        ),
    ]
