# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-14 01:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_spliceatom_minspeed'),
    ]

    operations = [
        migrations.AddField(
            model_name='spliceatom',
            name='SpeedAtSplice',
            field=models.IntegerField(null=True),
        ),
    ]
